config/routes.rb
Rails.application.routes.draw do
  resources :rates
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'    
   end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "home/manage" => "home/manage"
  post "home/manage" => "home/manage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rate.rb
class Rate < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :rates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index

        require 'net/http'
        require 'json'

        currency_to = "usd"
        currency_from = "eur"
    
        @url = "https://api.apilayer.com/fixer/convert?to=#{currency_to}&from=#{currency_from}&amount=100&apikey=aySd4XJBlaFfw1Z31bKPP8aPX0UrO7LY"
        @uri = URI(@url)
    
        @response = Net::HTTP.get(@uri)
        @currency = JSON.parse(@response)

        # Check for empty inputs

        if @currency.empty?
            @from_output = "N/A (You need to enter a pair to calculate rate"
            @to_output = "N/A (You need to enter a pair to calculate rate"
            @rate_output = "N/A (You need to enter a pair to calculate rate"
        elsif !@currency
            @from_output = "N/A (You need to enter a pair to calculate rate"
            @to_output = "N/A (You need to enter a pair to calculate rate"
            @rate_output = "N/A (You need to enter a pair to calculate rate"
        else
            @from_output = @currency["query"]["from"]
            @to_output = @currency["query"]["to"]
            @rate_output = @currency["info"]["rate"]
        end
    end

    def manage
        @fromparam = params[:fromcurrency].to_s
        @toparam = params[:tocurrency].to_s

        if params[:fromcurrency] && params[:tocurrency] == ""
            @from_output = "N/A"
            @to_output = "N/A"
            @rate_output = "N/A"
        elsif params[:fromcurrency] && params[:tocurrency]
            require 'net/http'
            require 'json'
            
            @url = "https://api.apilayer.com/fixer/convert?to=#{@toparam}&from=#{@fromparam}&amount=100&apikey=aySd4XJBlaFfw1Z31bKPP8aPX0UrO7LY"
            @uri = URI(@url)
            
            @response = Net::HTTP.get(@uri)
            @currency = JSON.parse(@response)
    
            @from_output = @currency["query"]["from"]
            @to_output = @currency["query"]["to"]
            @rate_output = @currency["info"]["rate"]
        end

    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ show edit update destroy ]


  # GET /rates or /rates.json
  def index
    @rates = Rate.all

    @fromparam = params[:from_symbol]
    @toparam = params[:to_symbol]

    if params[:fromcurrency] && params[:tocurrency] == ""
        @from_output = "N/A"
        @to_output = "N/A"
        @rate_output = "N/A"
    elsif params[:fromcurrency] && params[:tocurrency]
        require 'net/http'
        require 'json'
        
        @url = "https://api.apilayer.com/fixer/convert?to=#{@toparam}&from=#{@fromparam}&amount=100&apikey=aySd4XJBlaFfw1Z31bKPP8aPX0UrO7LY"
        @uri = URI(@url)
        
        @response = Net::HTTP.get(@uri)
        @currency = JSON.parse(@response)

        if @currency.empty?
          @from_output = "N/A (You need to enter a pair to calculate rate"
          @to_output = "N/A (You need to enter a pair to calculate rate"
          @rate_output = "N/A (You need to enter a pair to calculate rate"
        elsif !@currency
          @from_output = "N/A (You need to enter a pair to calculate rate"
          @to_output = "N/A (You need to enter a pair to calculate rate"
          @rate_output = "N/A (You need to enter a pair to calculate rate"
        else
          @from_output = @currency["query"]["from"]
          @to_output = @currency["query"]["to"]
          @rate_output = @currency["info"]["rate"]
        end


    end

  end

  # GET /rates/1 or /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates or /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to rate_url(@rate), notice: "Rate was successfully created." }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1 or /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to rate_url(@rate), notice: "Rate was successfully updated." }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1 or /rates/1.json
  def destroy
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url, notice: "Rate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rate_params
      params.require(:rate).permit(:from_symbol, :to_symbol, :rate_symbol, :user_id)
    end
    def correct_user
      @correct = current_user.rates.find_by(id: params[:id])
      redirect_to rates_path, notice: "You are not authorized" if @correct.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'Currency App', root_path, class:"navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Manage', home_manage_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, class:"nav-link", :method => :delete  %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Show Your Rates', rates_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Add New Pair', new_rate_path, class:"nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/_notice.html.erb
<br>
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/index.html.erb
<table class="table caption-top">
  <h1>Curreny Rates</h1>  
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Rate</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= @from_output %> </td>
      <td><%= @to_output %> </td>
      <td><%= @rate_output %> </td>
    </tr>
  </tbody>
</table>

app/views/home/manage.html.erb
<br>
<%= form_tag home_manage_path, data: { turbo: false }, :method => 'POST' do %>
    <div class="card" style="width: 36rem; margin:0 auto;">
        <div class="card-body">  <br>
            <%= select_tag 'fromcurrency', options_for_select([ "USD", "EUR", "TRY", "CAD", "GBP", "JPY", "QAR", "AED",  ], "USD"), class: "form-select" %> <br>
            <%= select_tag 'tocurrency', options_for_select([ "USD", "EUR", "TRY", "CAD", "GBP", "JPY", "QAR", "AED",  ], "EUR"), class: "form-select" %> <br>
            <%= submit_tag 'Search', class: "btn btn-outline-success"%> <br>
        </div>
    </div>
<% end %>

<br>

<table class="table caption-top" style="width: 36rem; margin:0 auto;">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Rate</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= @from_output %> </td>
      <td><%= @to_output %> </td>
      <td><%= @rate_output %> </td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CurrencyApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <%= render 'home/header' %>
    <%= render 'home/notice' %>
    <%= yield %>
  </body>
</html>

app/views/rates/_form.html.erb
<%= form_with(model: rate) do |form| %>
  <% if rate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
        <% rate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.select :from_symbol, (["USD", "EUR", "TRY", "CAD", "GBP", "JPY", "QAR", "AED"])%>
  </div>

  <div>
    <%= form.select :to_symbol, (["USD", "EUR", "TRY", "CAD", "GBP", "JPY", "QAR", "AED"])%>
  </div>

  <div>
    <%= form.text_field :rate_symbol, type: "hidden" %>
  </div>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rates/_rate.html.erb
<div id="<%= dom_id rate %>">
  <p>
    <strong>From symbol:</strong>
    <%= rate.from_symbol %>
  </p>

  <p>
    <strong>To symbol:</strong>
    <%= rate.to_symbol %>
  </p>

  <p>
    <strong>Rate symbol:</strong>
    <%= rate.rate_symbol %>
  </p>

  <p>
    <strong>User:</strong>
    <%= rate.user_id %>
  </p>

</div>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render "form", rate: @rate %>

<br>

<div>
  <%= link_to "Show this rate", @rate %> |
  <%= link_to "Back to rates", rates_path %>
</div>

app/views/rates/index.html.erb
<h1>Rates</h1>
<div id="rates">
    <% @rates.each do |rate| %>
      <% if rate.user_id == current_user.id%>
      <p>
        <strong>From symbol:</strong>
        <%= rate.from_symbol %>
      </p>
  
      <p>
        <strong>To symbol:</strong>
        <%= rate.to_symbol %>
     </p>
     <p>
      <strong>Rate symbol:</strong>
      <% require 'net/http' %>
      <% require 'json' %>
      <% @url = "https://api.apilayer.com/fixer/convert?to=#{rate.to_symbol}&from=#{rate.from_symbol}&amount=100&apikey=aySd4XJBlaFfw1Z31bKPP8aPX0UrO7LY" %>
      <% @uri = URI(@url) %>
      <% @response = Net::HTTP.get(@uri) %>
      <% @currency = JSON.parse(@response) %>
      <%= @rate_output = @currency["info"]["rate"] %>
     </p>
      <p>
        <%= button_to "Destroy this pair", rate, method: :delete, class: "btn btn-outline-danger" %>
      </p>
      <% end %>
    <% end %>
</div>


<%= link_to "New rate", new_rate_path %>

app/views/rates/new.html.erb
<h1>New rate</h1>

<%= render "form", rate: @rate %>

<br>

<div>
  <%= link_to "Back to rates", rates_path %>
</div>

app/views/rates/show.html.erb
<p>
<strong>From symbol:</strong>
<%= @rate.from_symbol %>
</p>

<p>
<strong>To symbol:</strong>
<%= @rate.to_symbol %>
</p>

<div>
  <%= link_to "Edit this rate", edit_rate_path(@rate) %> |
  <%= link_to "Back to rates", rates_path %>

  <%= button_to "Destroy this rate", @rate, method: :delete %>
</div>